spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
    #jpa:
    #show-sql: true
# 멀티 데이터베이스 설정
  datasource1:
    hikari:
      username: root
      password: root1234
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/arthall?characterEncoding=utf8
#  datasource2:
#    hikari:
#      username: root
#      password: root1234
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/con_node?characterEncoding=utf8
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

logging:
  level:
    jdbc.sqlonly: DEBUG

jwt:
  secret: jwtsecretkey


# 이건 왜 적용이 안되는지를 모르것네
#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  configuration:
#    map-underscore-to-camel-case: true