spring:
#  jpa:
#    show-sql: true
  datasource:
    hikari:
      username: root
      password: root1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/arthall?characterEncoding=utf8
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

logging:
  level:
    jdbc.sqlonly: DEBUG

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true